name: Build and Commit Changes

on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add -A
          git reset node_modules

          if ! git diff --cached --quiet; then
            git diff --cached --name-only | while read -r file; do
              git commit -m "Add $file :inbox_tray:" -- "$file"
            done

            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit."
          fi
